Repository ultralytics/petsys, pull requests merged in 2025-01, with the labels that each got.

#27 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
Labels: enhancement, devops

#28 Standardize license headers in Python files
  test_singles.py
Labels: documentation

#29 Standardize license headers in TOML/YAML files
  .github/workflows/format.yml
Labels: devops, documentation
